export const IT_DEPARTMENTS = [
  "Computer Science",
  "Information Technology",
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "Full Stack Development",
  "Frontend Development",
  "Backend Development",
  "Data Science",
  "Data Analytics",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Cloud Computing",
  "DevOps",
  "Networking",
  "Database Management",
  "Software Testing / QA",
  "UI/UX Design",
  "IT Support",
  "System Administration",
  "IT Infrastructure",
  "ERP / CRM",
  "Blockchain",
  "Game Development",
  "Technical Support",
  "Product Engineering",
  "Computer Engineering",
  "Embedded Systems",
  "Internet of Things (IoT)"
];

export const NON_IT_DEPARTMENTS = [
  "Human Resources (HR)",
  "Recruitment",
  "Finance",
  "Accounting",
  "Sales",
  "Marketing",
  "Digital Marketing",
  "Business Development",
  "Customer Service",
  "Customer Support",
  "Administration",
  "Operations",
  "Logistics",
  "Supply Chain Management",
  "Procurement",
  "Manufacturing",
  "Production",
  "Quality Control",
  "Quality Assurance",
  "Warehouse",
  "Retail",
  "Banking",
  "Insurance",
  "Healthcare",
  "Pharmaceutical",
  "Biotechnology",
  "Education",
  "Legal",
  "Real Estate",
  "Construction",
  "Architecture",
  "Automobile",
  "Mechanical",
  "Civil",
  "Electrical",
  "Electronics",
  "Chemical",
  "Agriculture",
  "Hospitality",
  "Travel & Tourism",
  "Media & Entertainment",
  "Content & Writing",
  "Public Relations",
  "Event Management",
  "Research & Development",
  "Design & Creative",
  "Back Office",
  "Data Entry",
  "BPO / KPO",
  "Telecalling",
  "Field Operations",
  "Government / Public Sector",
  "Office Administration",
  "Front Office",
  "Procurement & Vendor Management",
  "Facility Management",
  "Customer Relationship Management (CRM)"
];

export const IT_ROLES = [
  "Software Developer",
  "Full Stack Developer Java",
  "Full Stack Developer Python",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "Python Developer",
  "Java Developer",
  ".NET Developer",
  "PHP Developer",
  "React Developer",
  "Node.js Developer",
  "UI/UX Designer",
  "Data Analyst",
  "Data Scientist",
  "Business Analyst",
  "AI/ML Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Cybersecurity Analyst",
  "Network Engineer",
  "System Administrator",
  "Database Administrator",
  "QA Engineer",
  "Software Tester",
  "Automation Tester",
  "Technical Support Engineer",
  "IT Support Executive",
  "IT Project Manager",
  "Product Manager",
  "Scrum Master",
  "Solutions Architect",
  "Blockchain Developer",
  "Game Developer",
  "SEO Specialist",
  "Digital Marketing Specialist",
  "Content Writer",
  "Technical Writer"
];

export const NON_IT_ROLES = [
  "HR Executive",
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Executive",
  "Payroll Executive",
  "Accountant",
  "Finance Executive",
  "Financial Analyst",
  "Banking Executive",
  "Insurance Executive",
  "Sales Executive",
  "Sales Manager",
  "Business Development Executive",
  "Business Development Manager",
  "Marketing Executive",
  "Marketing Manager",
  "Digital Marketing Executive",
  "Customer Care Executive",
  "Customer Support Executive",
  "Telecaller",
  "Back Office Executive",
  "Data Entry Operator",
  "Office Administrator",
  "Administrative Executive",
  "Receptionist",
  "Front Office Executive",
  "Operations Executive",
  "Operations Manager",
  "Logistics Executive",
  "Supply Chain Executive",
  "Procurement Executive",
  "Purchase Executive",
  "Store Manager",
  "Warehouse Executive",
  "Inventory Executive",
  "Retail Sales Executive",
  "Store Executive",
  "Relationship Manager",
  "Account Manager",
  "Legal Executive",
  "Legal Assistant",
  "Content Writer",
  "Copywriter",
  "Graphic Designer",
  "Video Editor",
  "Social Media Executive",
  "Social Media Manager",
  "Teacher",
  "Tutor",
  "Trainer",
  "School Coordinator",
  "Healthcare Executive",
  "Medical Representative",
  "Hospital Administrator",
  "Pharmacist",
  "Lab Technician",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Production Engineer",
  "Quality Control Executive",
  "Quality Assurance Executive",
  "Manufacturing Executive",
  "Site Engineer",
  "Architect",
  "Interior Designer",
  "Real Estate Executive",
  "Hotel Manager",
  "Chef",
  "Restaurant Manager",
  "Hospitality Executive",
  "Travel Consultant",
  "Customer Relationship Executive"
];

export const DEGREES = {
  "Undergraduate": [
    "B.A. - Bachelor of Arts",
    "B.Sc. - Bachelor of Science",
    "B.Com. - Bachelor of Commerce",
    "B.B.A. - Bachelor of Business Administration",
    "B.C.A. - Bachelor of Computer Applications",
    "B.E. - Bachelor of Engineering",
    "B.Tech. - Bachelor of Technology",
    "B.Arch. - Bachelor of Architecture",
    "B.Des. - Bachelor of Design",
    "B.Pharm. - Bachelor of Pharmacy",
    "B.Sc. Nursing",
    "B.S.W. - Bachelor of Social Work",
    "B.Ed. - Bachelor of Education",
    "LL.B. - Bachelor of Laws",
    "MBBS",
    "B.D.S. - Bachelor of Dental Surgery",
    "BPT - Bachelor of Physiotherapy",
    "B.V.Sc. - Bachelor of Veterinary Science",
    "B.H.M. - Bachelor of Hotel Management"
  ],
  "Postgraduate": [
    "M.A. - Master of Arts",
    "M.Sc. - Master of Science",
    "M.Com. - Master of Commerce",
    "M.B.A. - Master of Business Administration",
    "M.C.A. - Master of Computer Applications",
    "M.E. - Master of Engineering",
    "M.Tech. - Master of Technology",
    "M.Arch. - Master of Architecture",
    "M.Des. - Master of Design",
    "M.Pharm. - Master of Pharmacy",
    "M.Ed. - Master of Education",
    "LL.M. - Master of Laws",
    "M.S.W. - Master of Social Work",
    "M.Phil.",
    "M.D.",
    "M.S. - Master of Surgery",
    "MPT - Master of Physiotherapy"
  ],
  "Diploma / Professional": [
    "Diploma",
    "Polytechnic Diploma",
    "ITI",
    "PG Diploma",
    "Advanced Diploma",
    "Professional Certification",
    "Vocational Certification"
  ]
};

export const GENERAL_DEPARTMENTS = [
  "General"
];

export const GENERAL_ROLES = [
  "General Candidate"
];
