export const ENGINEERING_DEPARTMENTS = [
  "Computer Science Engineering (CSE)",
  "Information Technology (IT)",
  "Artificial Intelligence & Data Science (AI & DS)",
  "Artificial Intelligence & Machine Learning (AI & ML)",
  "Electronics & Communication Engineering (ECE)",
  "Electrical & Electronics Engineering (EEE)",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Mechatronics Engineering",
  "Automobile Engineering",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Biotechnology Engineering",
  "Biomedical Engineering",
  "Instrumentation & Control Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Textile Technology",
  "Production Engineering",
  "Industrial Engineering",
  "Environmental Engineering",
  "Petroleum Engineering",
  "Mining Engineering",
  "Marine Engineering",
  "Robotics & Automation",
  "Information Science & Engineering (ISE)"
];

export const IT_DEPARTMENTS = ENGINEERING_DEPARTMENTS;

export const ARTS_AND_SCIENCE_DEPARTMENTS = [
  "Computer Science",
  "Information Technology",
  "Computer Applications",
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biotechnology",
  "Microbiology",
  "Biochemistry",
  "Zoology",
  "Botany",
  "Environmental Science",
  "Electronics",
  "Commerce",
  "Commerce with Computer Applications",
  "Accounting & Finance",
  "Business Administration",
  "Business Management",
  "Economics",
  "English",
  "Tamil",
  "History",
  "Political Science",
  "Sociology",
  "Psychology",
  "Social Work",
  "Geography",
  "Visual Communication",
  "Journalism & Mass Communication",
  "Hotel Management",
  "Tourism & Travel Management",
  "Fashion Design",
  "Interior Design",
  "Library & Information Science",
  "Physical Education"
];

export const NON_IT_DEPARTMENTS = ARTS_AND_SCIENCE_DEPARTMENTS;

export const IT_ROLES = [
  "Software Developer",
  "Full Stack Developer Java",
  "Full Stack Developer Python",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "Python Developer",
  "Java Developer",
  ".NET Developer",
  "PHP Developer",
  "React Developer",
  "Node.js Developer",
  "UI/UX Designer",
  "Data Analyst",
  "Data Scientist",
  "Business Analyst",
  "AI/ML Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Cybersecurity Analyst",
  "Network Engineer",
  "System Administrator",
  "Database Administrator",
  "QA Engineer",
  "Software Tester",
  "Automation Tester",
  "Technical Support Engineer",
  "IT Support Executive",
  "IT Project Manager",
  "Product Manager",
  "Scrum Master",
  "Solutions Architect",
  "Blockchain Developer",
  "Game Developer",
  "SEO Specialist",
  "Digital Marketing Specialist",
  "Content Writer",
  "Technical Writer"
];

export const NON_IT_ROLES = [
  "HR Executive",
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Executive",
  "Payroll Executive",
  "Accountant",
  "Finance Executive",
  "Financial Analyst",
  "Banking Executive",
  "Insurance Executive",
  "Sales Executive",
  "Sales Manager",
  "Business Development Executive",
  "Business Development Manager",
  "Marketing Executive",
  "Marketing Manager",
  "Digital Marketing Executive",
  "Customer Care Executive",
  "Customer Support Executive",
  "Telecaller",
  "Back Office Executive",
  "Data Entry Operator",
  "Office Administrator",
  "Administrative Executive",
  "Receptionist",
  "Front Office Executive",
  "Operations Executive",
  "Operations Manager",
  "Logistics Executive",
  "Supply Chain Executive",
  "Procurement Executive",
  "Purchase Executive",
  "Store Manager",
  "Warehouse Executive",
  "Inventory Executive",
  "Retail Sales Executive",
  "Store Executive",
  "Relationship Manager",
  "Account Manager",
  "Legal Executive",
  "Legal Assistant",
  "Content Writer",
  "Copywriter",
  "Graphic Designer",
  "Video Editor",
  "Social Media Executive",
  "Social Media Manager",
  "Teacher",
  "Tutor",
  "Trainer",
  "School Coordinator",
  "Healthcare Executive",
  "Medical Representative",
  "Hospital Administrator",
  "Pharmacist",
  "Lab Technician",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Production Engineer",
  "Quality Control Executive",
  "Quality Assurance Executive",
  "Manufacturing Executive",
  "Site Engineer",
  "Architect",
  "Interior Designer",
  "Real Estate Executive",
  "Hotel Manager",
  "Chef",
  "Restaurant Manager",
  "Hospitality Executive",
  "Travel Consultant",
  "Customer Relationship Executive"
];

export const DEGREES = {
  "Undergraduate": [
    "B.A. - Bachelor of Arts",
    "B.Sc. - Bachelor of Science",
    "B.Com. - Bachelor of Commerce",
    "B.B.A. - Bachelor of Business Administration",
    "B.C.A. - Bachelor of Computer Applications",
    "B.E. - Bachelor of Engineering",
    "B.Tech. - Bachelor of Technology",
    "B.Arch. - Bachelor of Architecture",
    "B.Des. - Bachelor of Design",
    "B.Pharm. - Bachelor of Pharmacy",
    "B.Sc. Nursing",
    "B.S.W. - Bachelor of Social Work",
    "B.Ed. - Bachelor of Education",
    "LL.B. - Bachelor of Laws",
    "MBBS",
    "B.D.S. - Bachelor of Dental Surgery",
    "BPT - Bachelor of Physiotherapy",
    "B.V.Sc. - Bachelor of Veterinary Science",
    "B.H.M. - Bachelor of Hotel Management"
  ],
  "Postgraduate": [
    "M.A. - Master of Arts",
    "M.Sc. - Master of Science",
    "M.Com. - Master of Commerce",
    "M.B.A. - Master of Business Administration",
    "M.C.A. - Master of Computer Applications",
    "M.E. - Master of Engineering",
    "M.Tech. - Master of Technology",
    "M.Arch. - Master of Architecture",
    "M.Des. - Master of Design",
    "M.Pharm. - Master of Pharmacy",
    "M.Ed. - Master of Education",
    "LL.M. - Master of Laws",
    "M.S.W. - Master of Social Work",
    "M.Phil.",
    "M.D.",
    "M.S. - Master of Surgery",
    "MPT - Master of Physiotherapy"
  ],
  "Diploma / Professional": [
    "Diploma",
    "Polytechnic Diploma",
    "ITI",
    "PG Diploma",
    "Advanced Diploma",
    "Professional Certification",
    "Vocational Certification"
  ]
};

export const GENERAL_DEPARTMENTS = [
  "General"
];

export const GENERAL_ROLES = [
  "General Candidate"
];
